server:
  shutdown: graceful

spring:
  h2:
    console:
      enabled: true

  # 데이터베이스 죽는 현상 참조 : https://kakaocommerce.tistory.com/45
  # 데이터베이스 누수 현상 해결하기 : https://do-study.tistory.com/97
  # datasource:
  #   url: jdbc:mysql://localhost:3306/github?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&autoReconnect=true
  #   dataSourceClassName: com.mysql.cj.jdbc.Driver 
  #   # driver-class-name: com.mysql.cj.jdbc.Driver 
  #   password: 1111 # 비밀번호 수정
  #   username: root

  datasource:
    hikari: 
      jdbc-url: jdbc:mysql://localhost:3306/github?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&autoReconnect=true
      dataSourceClassName: com.mysql.cj.jdbc.Driver 
      password: 1111 # 비밀번호 수정
      username: root



  devtools:
    livereload:
      enabled: true

  # 파일 관련 메소드
  thymeleaf:
    cache: false
  sql:
    init:
      encoding: UTF-8

# Mabatis 환경 설정 :
# 참조 : https://jydlove.tistory.com/49
# xml 대신 속성값으로 설정한다
mybatis:
  type-aliases-package: com.example.scroll_project_back.entity
  configuration:
    cache-enabled: true
    use-column-label: true
    use-generated-keys: false
    map-underscore-to-camel-case: true
    default-statement-timeout: 25000
    jdbc-type-for-null: NULL
  mapper-locations: classpath:/mapper/*Mapper.xml
  
logging:
  level:
    # root: debug
    # com.zaxxer.hikari.pool.HikariPool: debug
    org:
#      hibernate: info
      hibernate:
        type:
          descriptor:
            sql: trace